"""The held-out world pack and the confirmatory contract that freezes on it.

A new seed alone is not a held-out condition (benchmark_qc.md, Gate 1), and
the pilot that tuned the schema and prompt ran on every world of `worlds_v2`.
The confirmatory therefore runs on `worlds_v2_holdout`: the same generator
from a disjoint seed domain, sharing no case digest, knob signature or seed
label with the development pack.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

from aeread_families.datacenter_development.stack_worlds import (
    DEFAULT_OUTPUT_ROOT,
    STRATA,
    check_pack,
    load_pack_manifest,
)
from aeread_families.datacenter_development.world_campaign import (
    build_design,
    load_contract,
    pack_root_for,
    publication_root_for,
    run_root_for,
)

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
HOLDOUT_ROOT = REPOSITORY_ROOT / "cases" / "datacenter_development_v1" / "worlds_v2_holdout"
HOLDOUT_SEED = 20270920
HOLDOUT_PACK_ID = "datacenter_development_v2_worlds_holdout_v1"
CONFIRMATORY = REPOSITORY_ROOT / "configs" / "datacenter_development_v2_world_panel_confirmatory_v1.json"
FREEZE = REPOSITORY_ROOT / "configs" / "datacenter_development_v2_world_panel_confirmatory_v1.freeze.json"


def test_holdout_pack_is_reproducible_from_its_own_seed() -> None:
    result = check_pack(HOLDOUT_ROOT, master_seed=HOLDOUT_SEED, split="worlds_v2_holdout", pack_id=HOLDOUT_PACK_ID)
    assert result["reproducible"] is True and result["drift"] == []
    manifest = load_pack_manifest(HOLDOUT_ROOT)
    assert manifest["world_count"] == 24 and manifest["pack_id"] == HOLDOUT_PACK_ID
    assert {w["stratum"] for w in manifest["worlds"]} == set(STRATA)


def test_holdout_shares_nothing_with_the_development_pack() -> None:
    dev = load_pack_manifest(DEFAULT_OUTPUT_ROOT)
    hold = load_pack_manifest(HOLDOUT_ROOT)
    assert {w["content_sha256"] for w in dev["worlds"]}.isdisjoint({w["content_sha256"] for w in hold["worlds"]})
    knobs = lambda m: {json.dumps(w["knobs"], sort_keys=True) for w in m["worlds"]}
    assert knobs(dev).isdisjoint(knobs(hold))
    assert {w["world_seed"] for w in dev["worlds"]}.isdisjoint({w["world_seed"] for w in hold["worlds"]})
    assert {w["case_id"] for w in hold["worlds"]} == {
        f"datacenter_development_v1.worlds_v2_holdout.{w['file'].removesuffix('.json')}" for w in hold["worlds"]
    }


def test_a_generator_edit_that_keeps_every_world_is_still_reproducible() -> None:
    """The development pack was generated by an earlier revision of the
    generator; its worlds come back byte for byte and the generator digest
    difference is reported apart, not counted as drift."""

    result = check_pack(DEFAULT_OUTPUT_ROOT)
    assert result["reproducible"] is True and result["drift"] == []
    assert "generator_drift" in result


def test_confirmatory_contract_freezes_on_the_holdout() -> None:
    contract = load_contract(CONFIRMATORY)
    assert contract["campaign_id"] == "datacenter_development_v2_world_panel_confirmatory_v1"
    assert contract["pack_id"] == HOLDOUT_PACK_ID and contract["pack_split"] == "worlds_v2_holdout"
    assert contract["expected_pack_sha256"] == load_pack_manifest(HOLDOUT_ROOT)["artifact_sha256"]
    assert list(contract["models"]) == ["gemini38_flash_aistudio"]
    assert contract["inference_seeds"] == [51211, 51212, 51213]
    assert pack_root_for(contract) == HOLDOUT_ROOT
    assert run_root_for(contract).name == contract["campaign_id"]
    assert publication_root_for(contract) == REPOSITORY_ROOT / "evidence" / "datacenter_development" / contract["campaign_id"]

    design = build_design(contract, pack_root=HOLDOUT_ROOT)
    assert design["planned_cells"] == 24 * 3 == 72
    assert design["independent_cluster_count"] == 24
    assert design["worst_case_declared_cost_usd"] == pytest.approx(14.4)
    assert design["campaign_max_cost_usd"] == pytest.approx(15.0)

    freeze = json.loads(FREEZE.read_text())
    assert freeze["contract_sha256"] == hashlib.sha256(CONFIRMATORY.read_bytes()).hexdigest()
    assert freeze["pack_sha256"] == contract["expected_pack_sha256"]
    # The freeze pins the run as executed, and the record of execution is the
    # published design inside the sealed bundle, not a design rebuilt from
    # whatever the family source is today: a run plan pins the family
    # implementation by digest, so comparing the freeze to a fresh design
    # would fail on the first family edit after the run (DC-T-06). The fresh
    # design is held to what is independent of the source: the pack, the
    # contract, the cell count and the cost, within a cent (DC-T-05).
    published = json.loads((publication_root_for(contract) / "reports" / "design.json").read_text())
    assert freeze["campaign_driver_sha256"] == published["campaign_driver_sha256"]
    assert freeze["frozen_run_plan_sha256s"] == [cell["run_plan_sha256"] for cell in published["cells"]]
    assert freeze["design_artifact_sha256"] == published["artifact_sha256"]
    assert freeze["planned_cells"] == design["planned_cells"] == published["planned_cells"] == 72
    assert freeze["independent_cluster_count"] == design["independent_cluster_count"] == 24
    assert freeze["paired_seed_count"] == design["paired_seed_count"] == 3
    assert design["pack_sha256"] == published["pack_sha256"] == freeze["pack_sha256"]
    # The design hashes the contract as canonical JSON; the freeze hashes the
    # file bytes (asserted above). Both name the same contract.
    assert design["contract_sha256"] == published["contract_sha256"]
    assert [cell["case_sha256"] for cell in design["cells"]] == [cell["case_sha256"] for cell in published["cells"]]
    assert design["worst_case_declared_cost_usd"] == pytest.approx(14.4, abs=0.01)
    assert freeze["output_schema_bounded"] is True
    assert freeze["claims_allowed"]["winner"] is False


def test_the_pilot_contract_is_untouched_by_the_second_campaign() -> None:
    pilot = load_contract()
    assert pilot["campaign_id"] == "datacenter_development_v2_world_panel_v1"
    assert "pack_split" not in pilot and pack_root_for(pilot) == DEFAULT_OUTPUT_ROOT
    assert pilot["expected_pack_sha256"] == load_pack_manifest(DEFAULT_OUTPUT_ROOT)["artifact_sha256"]


def test_a_contract_outside_the_family_of_campaigns_is_refused(tmp_path) -> None:
    contract = json.loads(CONFIRMATORY.read_text())
    contract["campaign_id"] = "housing_v13_confirmatory"
    path = tmp_path / "wrong.json"
    path.write_text(json.dumps(contract), encoding="utf-8")
    with pytest.raises(ValueError, match="datacenter_development_v2_world_panel"):
        load_contract(path)
    contract = json.loads(CONFIRMATORY.read_text())
    contract["pack_split"] = "../worlds_v2"
    path.write_text(json.dumps(contract), encoding="utf-8")
    with pytest.raises(ValueError, match="pack_split"):
        load_contract(path)
