import { createRequire } from "node:module";
import { askClaude } from "../backend.mjs";
const C = createRequire(import.meta.url)("../src/core.js");
const S = C.newState();
C.addExpert(S, "I buy used construction equipment for a regional dealer. Senior buyer, been at it fourteen years.");
let r = await askClaude(C.turnPrompt(S));
console.log("turn 1:", r.seconds.toFixed(1) + "s");
let info = C.applyTurn(S, C.parseJson(r.text));
console.log(JSON.stringify(info), "|", S.transcript.at(-1).kind, "|", S.transcript.at(-1).text);
C.addExpert(S, "Mostly it's which machines to bid on at the online auctions, and then how to price them when we resell. Last one was an excavator, pretty pricey, I had it inspected and we won it. Usually the inspection catches pretty much everything.");
r = await askClaude(C.turnPrompt(S));
console.log("turn 2:", r.seconds.toFixed(1) + "s");
info = C.applyTurn(S, C.parseJson(r.text));
const m = S.transcript.at(-1);
console.log(JSON.stringify(info), "|", m.kind, m.reason || "", "|", m.text);
console.log("meta:", JSON.stringify(S.caseFile.meta));
console.log("decision:", JSON.stringify(S.caseFile.decision));
console.log("gaps:", S.gaps.map((g) => g.kind + ": " + g.text).join(" || "));
console.log("numbers:", JSON.stringify(S.numbers));
