"""Family-neutral execution infrastructure for AERead."""

from .event_store import (
    ArtifactIntegrityError,
    ArtifactStore,
    ConcurrentWriterError,
    EventIntegrityError,
    EventStore,
    EvidenceSealedError,
    EvidenceStoreError,
    InvalidEvidenceInput,
    recompute_event_hash,
)

from .planning import (
    ADMISSION_REQUIREMENTS,
    CapabilityMismatch,
    ContentHashMismatch,
    IncompleteAgentAssignment,
    InvalidAgentRequest,
    InvalidClusterDeclaration,
    ManifestMismatch,
    PlanningError,
    UnresolvedImplementation,
    build_agent_request_from_plan,
    evaluate_admission,
    resolve_run_plan,
    verify_run_plan_identity,
)
from .registry import (
    DuplicateReferenceImplementation,
    InvalidReferenceImplementation,
    PluginRegistry,
    ReferenceImplementationError,
    ReferenceImplementationHashMismatch,
    ReferenceImplementationRegistry,
    ReferenceImplementationRole,
    ReferenceImplementationRoleMismatch,
    ReferenceImplementationVersionMismatch,
    RegisteredReferenceImplementation,
    UnknownReferenceImplementation,
)
from .verifier_artifacts import (
    ConflictingReferenceArtifactDeclaration,
    InvalidReferenceArtifactInput,
    ReferenceArtifactError,
    ReferenceArtifactUnavailable,
    ReferenceArtifactView,
    UndeclaredReferenceArtifact,
    build_reference_artifact_view,
)

__all__ = [
    "ADMISSION_REQUIREMENTS",
    "ArtifactIntegrityError",
    "ArtifactStore",
    "CapabilityMismatch",
    "ConflictingReferenceArtifactDeclaration",
    "ContentHashMismatch",
    "ConcurrentWriterError",
    "DuplicateReferenceImplementation",
    "EventIntegrityError",
    "EventStore",
    "EvidenceSealedError",
    "EvidenceStoreError",
    "IncompleteAgentAssignment",
    "InvalidAgentRequest",
    "InvalidClusterDeclaration",
    "InvalidEvidenceInput",
    "InvalidReferenceArtifactInput",
    "InvalidReferenceImplementation",
    "ManifestMismatch",
    "PlanningError",
    "PluginRegistry",
    "ReferenceArtifactError",
    "ReferenceArtifactUnavailable",
    "ReferenceArtifactView",
    "ReferenceImplementationError",
    "ReferenceImplementationHashMismatch",
    "ReferenceImplementationRegistry",
    "ReferenceImplementationRole",
    "ReferenceImplementationRoleMismatch",
    "ReferenceImplementationVersionMismatch",
    "RegisteredReferenceImplementation",
    "UndeclaredReferenceArtifact",
    "UnknownReferenceImplementation",
    "UnresolvedImplementation",
    "build_agent_request_from_plan",
    "build_reference_artifact_view",
    "evaluate_admission",
    "resolve_run_plan",
    "recompute_event_hash",
    "verify_run_plan_identity",
]
