"""AERead shared-runner contracts and implementation stages."""

from .registry import PluginRegistry
from .resolver import (
    ImplementationPin,
    PlanCell,
    PlanIntegrityError,
    PlanResolutionError,
    RunPlan,
    canonical_json_bytes,
    case_content_sha256,
    resolve_run_plan,
    verify_run_plan,
    write_run_plan,
)
from .scheduler import (
    ActionEnvelope,
    DecisionRequest,
    EpisodeResult,
    LegalityResult,
    LogicalActionRecord,
    ParseResult,
    PhaseInstance,
    PhaseSpec,
    SchedulerContractError,
    TransitionResult,
    run_episode,
)
from .schemas import (
    AgentProfile,
    AnalysisPlan,
    AuthoringValidationError,
    CaseManifest,
    EvaluationBlock,
    FamilyManifest,
    RunSpec,
    SamplingPlan,
    SuiteManifest,
    parse_authoring_record,
)

__all__ = [
    "AgentProfile",
    "ActionEnvelope",
    "AnalysisPlan",
    "AuthoringValidationError",
    "CaseManifest",
    "EvaluationBlock",
    "EpisodeResult",
    "FamilyManifest",
    "ImplementationPin",
    "DecisionRequest",
    "LegalityResult",
    "LogicalActionRecord",
    "ParseResult",
    "PlanCell",
    "PlanIntegrityError",
    "PlanResolutionError",
    "PhaseInstance",
    "PhaseSpec",
    "PluginRegistry",
    "RunPlan",
    "RunSpec",
    "SchedulerContractError",
    "SamplingPlan",
    "SuiteManifest",
    "TransitionResult",
    "canonical_json_bytes",
    "case_content_sha256",
    "parse_authoring_record",
    "resolve_run_plan",
    "run_episode",
    "verify_run_plan",
    "write_run_plan",
]
