#!/usr/bin/env python3
"""Generate the family catalog from the tree and the plugin registry.

Three indexes used to be written by hand and all three went stale: the
family table in ``README.md`` listed three of twenty-one families, and
``cases/README.md`` missed nine of twenty-six case directories. They are
now generated, and ``tests/test_family_catalog.py`` fails when the
committed text differs from what this module produces.

    python tools/family_catalog.py            # check; exit 1 on drift
    python tools/family_catalog.py --write    # regenerate in place

What is derived, and from where:

* family packages, from ``src/aeread_families/`` (and ``aeread.exchange_v1``);
* registered identities, from ``TRUSTED_BUILTIN_PLUGIN_KEYS`` in the plugin
  registry, read as source so nothing is imported or executed;
* case directories, document directories and published bundles, from
  ``cases/``, ``docs/families/`` and ``evidence/``;
* versioned campaign modules and who still imports them, from the family
  packages' own file names and import statements.

What is declared here, because no file states it: one display name and one
kind per package (``FAMILIES``), and the document directory two packages
share (``SHARED_DOCUMENT_DIRECTORIES``). A package, case directory, document
directory or registered identity that this module cannot place is an error,
not a silent omission -- that is the property the hand-written tables lacked.
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

NATIVE = "native"
ADAPTER = "external adapter"

# package -> (display name, kind). Add a row when a family package is added.
FAMILIES: dict[str, tuple[str, str]] = {
    "agenticpay_bilateral": ("AgenticPay", ADAPTER),
    "alympics_wac": ("Alympics WAC", ADAPTER),
    "amazonbarg": ("AmazonHistoryPrice", ADAPTER),
    "aucarena": ("AucArena", ADAPTER),
    "collusion": ("Algorithmic collusion", ADAPTER),
    "commercial_state_calibration": ("Commercial state calibration", NATIVE),
    "consent_ir": ("Consent/IR", NATIVE),
    "datacenter_development": ("Data-center development", NATIVE),
    "datacenter_development_terms": ("Data-center development terms", NATIVE),
    "econagent_v1": ("EconAgent", ADAPTER),
    "econevals": ("EconEvals", ADAPTER),
    "exchange_v1": ("Exchange v1", "native, predates the shared runner"),
    "govsim": ("GovSim", ADAPTER),
    "housing": ("Housing", NATIVE),
    "negarena": ("NegotiationArena", ADAPTER),
    "procurement_allocation": ("Procurement allocation", NATIVE),
    "procurement_grounding": ("Procurement grounding", NATIVE),
    "refund": ("Refund", NATIVE),
    "single_offer": ("Single offer", "kernel smoke test"),
    "steer": ("STEER", ADAPTER),
    "tau3_retail": ("Tau3 retail", ADAPTER),
    "termsbench": ("TERMS-Bench", ADAPTER),
}

# docs/families/<directory> -> the packages it documents, where the name
# alone does not say.
SHARED_DOCUMENT_DIRECTORIES: dict[str, tuple[str, ...]] = {
    "datacenter": ("datacenter_development", "datacenter_development_terms"),
}

# Packages that live outside src/aeread_families/.
EXTRA_PACKAGES: dict[str, str] = {"exchange_v1": "src/aeread/exchange_v1"}

# evidence/ directories that belong to the kernel, not to a family. The errata
# records and their register (#117) span every family.
KERNEL_EVIDENCE_DIRECTORIES = frozenset({"shared_runner", "errata", "errata_register"})

README = "README.md"
CASES_README = "cases/README.md"
CAMPAIGN_MODULES = "docs/families/campaign_modules.md"

BEGIN = "<!-- family-catalog:begin (generated by tools/family_catalog.py; do not edit) -->"
END = "<!-- family-catalog:end -->"

_VERSION = re.compile(r"(?:^|_)v(\d+)(?=_|$)")
_VERSION_SUFFIX = re.compile(r"_v\d+$")


class CatalogError(RuntimeError):
    """The tree holds something this module cannot place."""


@dataclass
class Family:
    package: str
    name: str
    kind: str
    source: str
    identities: list[str] = field(default_factory=list)
    case_directories: list[str] = field(default_factory=list)
    document_directories: list[str] = field(default_factory=list)
    family_bundles: int = 0
    preserved_bundles: int = 0


def _directories(path: Path) -> list[str]:
    return sorted(
        child.name
        for child in path.iterdir()
        if child.is_dir() and not child.name.startswith((".", "__"))
    )


def _package_sources(root: Path) -> dict[str, str]:
    sources = {name: f"src/aeread_families/{name}" for name in _directories(root / "src/aeread_families")}
    sources.update(EXTRA_PACKAGES)
    return sources


def trusted_plugin_keys(root: Path) -> list[tuple[str, str, str]]:
    """``TRUSTED_BUILTIN_PLUGIN_KEYS`` as written, without importing the kernel."""
    module = ast.parse((root / "src/aeread/shared_runner/registry.py").read_text(encoding="utf-8"))
    for node in module.body:
        if not isinstance(node, ast.Assign):
            continue
        if any(getattr(target, "id", None) == "TRUSTED_BUILTIN_PLUGIN_KEYS" for target in node.targets):
            call = node.value
            if isinstance(call, ast.Call) and call.args:
                return sorted(ast.literal_eval(call.args[0]))
    raise CatalogError("TRUSTED_BUILTIN_PLUGIN_KEYS not found in the plugin registry")


def collect(root: Path = ROOT) -> tuple[list[Family], list[str]]:
    """Every family, and the registered identities no package on this tree declares."""
    sources = _package_sources(root)
    undeclared = sorted(set(sources) - set(FAMILIES))
    stale = sorted(set(FAMILIES) - set(sources))
    if undeclared or stale:
        raise CatalogError(
            f"FAMILIES in tools/family_catalog.py is out of step with the tree: "
            f"add {undeclared}, remove {stale}"
        )
    families = {
        package: Family(package, *FAMILIES[package], source=sources[package])
        for package in sorted(sources)
    }

    text = {
        package: "\n".join(
            path.read_text(encoding="utf-8") for path in sorted((root / source).rglob("*.py"))
        )
        for package, source in sources.items()
    }
    unowned: list[str] = []
    owner_of_family_id: dict[str, str] = {}
    for family_id, version, plugin_id in trusted_plugin_keys(root):
        literal = re.compile(r"[\"']" + re.escape(plugin_id) + r"[\"']")
        owners = [package for package, body in text.items() if literal.search(body)]
        label = f"{family_id}@{version}"
        if len(owners) > 1:
            raise CatalogError(f"{label} ({plugin_id}) is declared by several packages: {owners}")
        if not owners:
            unowned.append(label)
            continue
        families[owners[0]].identities.append(label)
        owner_of_family_id[family_id] = owners[0]

    for directory in _directories(root / "cases"):
        candidates = {directory, _VERSION_SUFFIX.sub("", directory)} & set(families)
        owner = next(iter(candidates), None) or owner_of_family_id.get(directory)
        if owner is None:
            raise CatalogError(
                f"cases/{directory} matches no family package by name or registered family id"
            )
        families[owner].case_directories.append(directory)

    for directory in _directories(root / "docs/families"):
        if directory in SHARED_DOCUMENT_DIRECTORIES:
            owners = list(SHARED_DOCUMENT_DIRECTORIES[directory])
        else:
            snake = directory.replace("-", "_")
            owners = [
                package
                for package in families
                if snake in (package, _VERSION_SUFFIX.sub("", package))
            ]
        if not owners:
            raise CatalogError(f"docs/families/{directory} matches no family package")
        for owner in owners:
            families[owner].document_directories.append(directory)

    by_length = sorted(families, key=len, reverse=True)
    for directory in _directories(root / "evidence"):
        if directory in KERNEL_EVIDENCE_DIRECTORIES:
            continue
        if directory in families:
            families[directory].family_bundles = len(_directories(root / "evidence" / directory))
            continue
        owner = next((p for p in by_length if directory.startswith(p + "_")), None)
        if owner is None:
            raise CatalogError(f"evidence/{directory} matches no family package")
        families[owner].preserved_bundles += 1

    return list(families.values()), unowned


def _links(prefix: str, names: list[str]) -> str:
    return ", ".join(f"[`{name}/`]({prefix}{name}/)" for name in names) or "none"


def family_table(families: list[Family], unowned: list[str]) -> str:
    lines = [
        "| Family | Kind | Package | Registered identities | Cases | Documents | Published bundles |",
        "|---|---|---|---|---|---|---:|",
    ]
    for family in sorted(families, key=lambda item: item.name.lower()):
        bundles = family.family_bundles + family.preserved_bundles
        if family.family_bundles:
            published = f"[{bundles}](evidence/{family.package}/)"
        else:
            published = str(bundles)
        lines.append(
            "| "
            + " | ".join(
                [
                    family.name,
                    family.kind,
                    f"[`{family.package}`]({family.source}/)",
                    ", ".join(f"`{identity}`" for identity in family.identities) or "none",
                    _links("cases/", family.case_directories),
                    _links("docs/families/", family.document_directories),
                    published,
                ]
            )
            + " |"
        )
    total = sum(f.family_bundles + f.preserved_bundles for f in families)
    lines += [
        "",
        f"{len(families)} families, {sum(len(f.case_directories) for f in families)} case "
        f"directories, {total} published bundles. A registered identity is a "
        "`family_id@version` in the kernel's trusted plugin keys.",
    ]
    if unowned:
        lines += [
            "",
            "Registered with no family package on this tree: "
            + ", ".join(f"`{label}`" for label in unowned)
            + ".",
        ]
    return "\n".join(lines)


def case_table(families: list[Family], root: Path) -> str:
    lines = ["| Case directory | Family | Package | Files |", "|---|---|---|---:|"]
    rows = sorted(
        (directory, family) for family in families for directory in family.case_directories
    )
    for directory, family in rows:
        files = sum(1 for path in (root / "cases" / directory).rglob("*") if path.is_file())
        lines.append(
            f"| [`{directory}/`]({directory}/) | {family.name} | "
            f"[`{family.package}`](../{family.source}/) | {files} |"
        )
    without = sorted(f.name for f in families if not f.case_directories)
    lines += ["", "Families with no case directory: " + ", ".join(without) + "."]
    return "\n".join(lines)


def _imported_modules(path: Path, package: str) -> set[str]:
    """Sibling module names a family module imports."""
    names: set[str] = set()
    for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
        if not isinstance(node, ast.ImportFrom):
            continue
        module = node.module or ""
        if node.level == 1:
            names.add(module.split(".")[0] if module else "")
            if not module:
                names.update(alias.name for alias in node.names)
        elif node.level == 0 and module.startswith(f"aeread_families.{package}"):
            rest = module[len(f"aeread_families.{package}") :].lstrip(".")
            if rest:
                names.add(rest.split(".")[0])
            else:
                names.update(alias.name for alias in node.names)
    names.discard("")
    return names


def campaign_modules_page(root: Path = ROOT) -> str:
    out = [
        "# Versioned campaign modules",
        "",
        "**Generated by `tools/family_catalog.py`; do not edit.**",
        "",
        "A changed frozen control is a new campaign identity, never a rerun in place,",
        "so a family that revises a campaign adds a module beside the old one",
        "(`adoption_campaign.py`, `adoption_campaign_v2.py`, `adoption_campaign_v3.py`).",
        "The result is many near-identical files in one package. This page lists every",
        "such line: its latest version, its other versions, and how many sibling",
        "modules still import each of those.",
        "",
        "**Revise a campaign by adding the next version, and start it from the latest.",
        "Do not edit, move or delete the others.** Campaign drivers record their own",
        "source digest, and their siblings', in the bundles they publish, and they",
        "locate those siblings and the repository root relative to their own path.",
        "Editing a listed module, or moving it into a subpackage, changes bytes that",
        "published evidence names. Later versions also import earlier ones, so an",
        "earlier module is frozen, not dead.",
        "",
        "Latest means the highest version number. It is not always a replacement:",
        "where a family keeps a case directory for each version, each is still run.",
        "",
    ]
    families_root = root / "src/aeread_families"
    for package in _directories(families_root):
        modules = sorted(path for path in (families_root / package).glob("*.py"))
        importers: dict[str, set[str]] = defaultdict(set)
        for path in modules:
            for name in _imported_modules(path, package):
                importers[name].add(path.stem)
        lines: dict[str, dict[int, str]] = defaultdict(dict)
        for path in modules:
            match = _VERSION.search(path.stem)
            line = re.sub(r"__+", "_", _VERSION.sub("", path.stem)).strip("_") if match else path.stem
            lines[line][int(match.group(1)) if match else 1] = path.stem
        versioned = {line: versions for line, versions in lines.items() if len(versions) > 1}
        if not versioned:
            continue
        out += [
            f"## `{package}`",
            "",
            "| Line | Latest | Other versions | Still imported by siblings |",
            "|---|---|---|---|",
        ]
        for line in sorted(versioned):
            versions = versioned[line]
            current = max(versions)
            link = f"../../src/aeread_families/{package}"
            earlier = [v for v in sorted(versions) if v != current]
            still = [
                f"v{v} by {len(importers[versions[v]] - {versions[v]})}"
                for v in earlier
                if importers[versions[v]] - {versions[v]}
            ]
            out.append(
                f"| `{line}` | v{current}: [`{versions[current]}.py`]({link}/{versions[current]}.py) | "
                + ", ".join(f"[v{v}]({link}/{versions[v]}.py)" for v in earlier)
                + " | "
                + (", ".join(still) or "none")
                + " |"
            )
        out.append("")
    return "\n".join(out)


def _replace_block(text: str, body: str, path: str) -> str:
    if text.count(BEGIN) != 1 or text.count(END) != 1:
        raise CatalogError(f"{path} must contain exactly one generated block")
    head, rest = text.split(BEGIN)
    _, tail = rest.split(END)
    return f"{head}{BEGIN}\n\n{body}\n\n{END}{tail}"


def generate(root: Path = ROOT) -> dict[str, str]:
    """Path -> the text that file must hold."""
    families, unowned = collect(root)
    return {
        README: _replace_block(
            (root / README).read_text(encoding="utf-8"), family_table(families, unowned), README
        ),
        CASES_README: _replace_block(
            (root / CASES_README).read_text(encoding="utf-8"),
            case_table(families, root),
            CASES_README,
        ),
        CAMPAIGN_MODULES: campaign_modules_page(root),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    parser.add_argument("--write", action="store_true", help="regenerate the files in place")
    arguments = parser.parse_args(argv)
    try:
        expected = generate(ROOT)
    except CatalogError as error:
        print(f"family catalog: {error}", file=sys.stderr)
        return 2
    drifted = [
        path
        for path, text in expected.items()
        if not (ROOT / path).is_file() or (ROOT / path).read_text(encoding="utf-8") != text
    ]
    if arguments.write:
        for path in drifted:
            (ROOT / path).write_text(expected[path], encoding="utf-8")
            print(f"wrote {path}")
        return 0
    for path in drifted:
        print(f"stale: {path} (run python tools/family_catalog.py --write)", file=sys.stderr)
    return 1 if drifted else 0


if __name__ == "__main__":
    raise SystemExit(main())
